[Design/#29] Build CTAButton Design System
DeveloperAcademy-POSTECH/MacC-Team2-Nutty pull request #38
Opened 2023-10-11 07:34 UTC by ge-um

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- #29 

👷 **작업한 내용**
- CTAButton 일단 작업한 내용 올립니다. 

## 🚨 참고 사항
- TextStyle 적용 안 돼서 직접 넣었어요.. 이거 어떻게 해야 함? 
- RadioButton 아직 작업 안했어요~ 
- 버튼 그대로 사용하시라고 sampleView에 사용 형식 넣어 뒀어요~
- 위의 check는 비활성화 버튼입니다.  

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|CTAButton|![Uploading CTAButton.gif…]()
||<img src = "">

## 📟 관련 이슈
- Resolved: #

2023-10-11 15:34 UTC, JJunghyunY requested changes
동적 사이즈 조절 관련해서 저도 찾아볼께요

2023-10-11 15:34 UTC, JJunghyunY commented on Onbom/Onbom/Components/CTAButton.swift
> +    struct CustomButtonView<CustomLabelType: View>: View {
유연성 고려해서 제네릭 쓰신것같은데, 제네릭 지우고 아래 CustomLabelType을 Text만 받게 하면
label에 Text관련 Extension 메소드 사용할 수 있긴 할것같아요
만약 나중에 Text하나만 받지 않는 요상한 CTA버튼이 생기면 그땐 그 버튼에 CTAButtonStyleModifiers만 주고 그 버튼에서 label수정하는식으로 할 수 있으니까요

2023-10-11 15:34 UTC, JJunghyunY commented on Onbom/Onbom/Components/CTAButton.swift
> +            HStack {
이건 같이 고민좀 해보죠

2023-10-12 07:23 UTC, ge-um commented on Onbom/Onbom/Components/CTAButton.swift
> +    struct CustomButtonView<CustomLabelType: View>: View {
넹~

2023-10-16 08:51 UTC, JJunghyunY approved these changes

2023-10-16 08:52 UTC, merged